version: '3.7'
services:
  app:
    image: n4zim/react-quick-start-stack:latest
    build: .
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - "${WEB_PORT}:80"
    restart: always
